#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, make this file executable.

echo 'Compiling Emacs autoloads and byte-compiling Elisp...'
emacs --batch --eval '
(let ((make-backup-files nil)
      (generated-autoload-file "~/.elisp/my-loaddefs.el")
      (byte-compile-warnings nil)
      (byte-compile-verbose nil)
      (noninteractive t)
      (dirs '\''("~/.elisp" "~/.elisp/ocaml" "~/.elisp/auctex/preview"
                 "~/.elisp/auctex" "~/.elisp/haskell-mode"))
      (elpa-dirs (directory-files "~/.elisp/elpa" '\''full "-\\([0-9]\\.?\\)+"))
      (load-only-dirs '\''("~/.elisp/nxhtml" "~/.elisp/nxhtml/nxhtml"
                           "~/.elisp/nxhtml/util" "~/.elisp/nxhtml/related")))
  (setq load-path (append dirs elpa-dirs load-only-dirs load-path))
  (dolist (dir dirs) (update-directory-autoloads dir))
  (byte-recompile-directory "~/.elisp" 0))
' &> /dev/stdout | grep -v '^\(Checking\|Compiling\|Saving\|Loading\|Wrote\|Warning: defvar ignored\|(No changes need to be saved)\)'
