#!/bin/sh
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, make this file executable.

emacs --batch --eval '
(progn
  (setq make-backup-files nil)
  (setq generated-autoload-file "~/.elisp/my-loaddefs.el")
  (update-directory-autoloads "~/.elisp")
  (update-directory-autoloads "~/.elisp/haskell-mode")
  (update-directory-autoloads "~/.elisp/auctex")
  (update-directory-autoloads "~/.elisp/ocaml")
  (update-directory-autoloads "~/.elisp/fuel")

  (byte-compile-file "~/.elisp/byte-code-cache.el"))
'
