(cd (file-name-parent-directory (file-name-directory load-file-name)))
(let ((make-backup-files nil)
      (byte-compile-warnings nil)
      (byte-compile-verbose nil)
      (noninteractive t)
      (dirs (list (expand-file-name "elisp")))
      (elpa-dirs (directory-files "elisp/elpa" 'full "-\\([0-9]\\.?\\)+")))
  (setq load-path (append dirs elpa-dirs load-path))
  (loaddefs-generate dirs "elisp/my-loaddefs.el")
  (byte-recompile-directory "elisp" 0))
