;;; ssass-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ssass-mode.el

(autoload 'ssass-mode "ssass-mode" "\
Major mode for Sass

(fn)" t)
(register-definition-prefixes "ssass-mode" '("ssass-"))

;;; End of scraped data

(provide 'ssass-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ssass-mode-autoloads.el ends here
