;;; pager-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from pager.el

(autoload 'pager-page-down "pager" "\
Like scroll-up, but moves a fixed amount of lines (fixed relative the
`window-height') so that pager-page-up moves back to the same line." t)
(autoload 'pager-page-up "pager" "\
Like scroll-down, but moves a fixed amount of lines (fixed relative the
`window-height') so that pager-page-down moves back to the same line." t)
(autoload 'pager-row-up "pager" "\
Move point to previous line while scrolling screen down one line.
The effect is that the cursor stays in the same position on the screen." t)
(autoload 'pager-row-down "pager" "\
Move point to next line while scrolling screen up one line.
The effect is that the cursor stays in the same position on the screen." t)
(register-definition-prefixes "pager" '("pager-" "pg-" "row-"))

;;; End of scraped data

(provide 'pager-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pager-autoloads.el ends here
